kind: PersitentVolumeClaim
apiVersion: v1

metadata:
  name: mysql-pvc
  namesapce: mysql


spec: 
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  resource: 
    requests:
      storgae: 2Gi
      